use_frameworks!

target 'UniversalExtensions_Example' do
  pod 'UniversalExtensions', :path => '../'

  target 'UniversalExtensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
